### ISSUE TITLE
Error when tried running 

### ISSUE THREAD

**Issue by Anush-Onkar** [awaistanveerkhan/Internships#1]
Hey, tried running the code for **Personalized Medicine Recommendation System** and facing this error 

Traceback (most recent call last):
  File "app.py", line 17, in <module>
    model = joblib.load(model_path)
  File "/home/anush/miniconda3/envs/ecoki_dev/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/anush/miniconda3/envs/ecoki_dev/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/home/anush/miniconda3/envs/ecoki_dev/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
KeyError: 0

do you know why is this error popping up? thanks in advance

**Comment by awaistanveerkhan** [comment]
Yes, because that model path is of my local device. You need to update the
local path according to your PC and then try again.
